// examples/chat-vue/src/App.vue
<template>
  <AppContainer>
    <TopBar v-if="me">
      <p>{{ me.profile?.name }}</p>
      <button @click="logOut">Log out</button>
    </TopBar>
    <router-view />
  </AppContainer>
</template>

<script setup lang="ts">
import AppContainer from "./components/AppContainer.vue";
import TopBar from "./components/TopBar.vue";
import { useAccount } from "./main";

const { me, logOut } = useAccount();
</script>

// examples/image-upload/src/App.tsx
import ImageUpload from "./ImageUpload.tsx";
import { useAccount } from "./main";

function App() {
  const { me, logOut } = useAccount();

  return (
    <>
      <header>
        <nav className="container">
          <span>
            You're logged in as <strong>{me?.profile?.name}</strong>
          </span>
          <button onClick={() => logOut()}>Log out</button>
        </nav>
      </header>
      <main className="container">
        <ImageUpload />
      </main>
    </>
  );
}

export default App;
